import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    title: "Seva Setu AI",
    tagline: "Government Services. One Conversation Away.",
    navHome: "Home",
    navDashboard: "Dashboard",
    navChat: "AI Assistant",
    navSchemes: "Schemes",
    navComplaints: "Complaints",
    navDocuments: "Documents",
    navProfile: "Profile",
    navSettings: "Settings",
    navAbout: "About",
    login: "Login",
    register: "Register",
    logout: "Logout",
    startTalking: "Start Talking",
    tryDemo: "Try Demo",
    heroHeading: "Government Services Made Simple with AI",
    heroSubheading: "Speak naturally in your local language. Search government schemes, generate formal complaints, and discover documents easily.",
    featuresTitle: "Why Choose Seva Setu?",
    voiceFirst: "Voice-First AI",
    voiceFirstDesc: "Talk in English, Hindi, or Marathi. No typing required.",
    docChecklist: "Document Checklist",
    docChecklistDesc: "Instant lists of documents required for passport, ration card, etc.",
    complaints: "Voice Complaints",
    complaintsDesc: "Describe your civic issue. AI drafts a formal complaint automatically.",
    schemes: "Scheme Advisor",
    schemesDesc: "Enter your age, income, and profession to find matching welfare schemes.",
    simpleLang: "Explain Simply (ELI12)",
    simpleLangDesc: "Read complex procedures in plain, jargon-free words.",
    accessible: "High Accessibility",
    accessibleDesc: "Built for senior citizens, low literacy, and high contrast visibility.",
    voiceWaveforms: "Voice Waves",
    waveformPlaying: "Speaking response aloud...",
    stopSpeaking: "Stop Speaking",
    listen: "Listen",
    askQuestion: "Ask Seva Setu anything...",
    micTooltip: "Click to speak",
    listening: "Listening... speak now",
    processing: "Thinking...",
    normalView: "Detailed Explanation",
    simpleView: "Simplified (ELI12)",
    summaryView: "Quick Summary",
    complaintDraft: "Generated Complaint Draft",
    complaintDept: "Target Department",
    complaintSubject: "Subject",
    complaintIssue: "Issue",
    complaintDesc: "Official Description",
    complaintPriority: "Priority",
    submitComplaint: "Submit Complaint",
    complaintSuccess: "Complaint submitted successfully!",
    schemeMatch: "Personalized Schemes for You",
    schemeEligibility: "Who can apply:",
    schemeBenefits: "Benefits:",
    schemeSteps: "Application steps:",
    saveScheme: "Bookmark Scheme",
    savedSchemes: "Bookmarked Schemes",
    recentConversations: "Recent Conversations",
    quickActions: "Quick Actions",
    contrastToggle: "High Contrast Mode",
    textSizeToggle: "Text Size",
    textSmall: "A-",
    textNormal: "A",
    textLarge: "A+",
    howItWorksTitle: "How Seva Setu Works",
    howItWorksStep1Title: "Speak naturally",
    howItWorksStep1Desc: "Tap the mic and speak in English, Hindi, or Marathi. AI translates and queries the guidelines.",
    howItWorksStep2Title: "Explain Simply",
    howItWorksStep2Desc: "Toggle between standard, ELI12 simplified, or quick bullet points. Have answers read aloud.",
    howItWorksStep3Title: "Save Progress",
    howItWorksStep3Desc: "Check off completed checklist items and bookmark recommended schemes directly to your profile.",
    featuresSub: "Tailored for accessibility and digital inclusion",
    langSupport: "English, हिंदी & मराठी supported",
    heroTitleStart: "Your Personal",
    heroTitleEnd: "AI Government Assistant",
    heroDescription: "Helping every Indian citizen access government services, discover schemes, file complaints, and understand official documents in their own language.",
    trustVoice: "Voice First",
    trustLang: "Multilingual",
    trustSecure: "Secure",
    trustAI: "AI Powered",
    aboutTitle: "About Seva Setu AI",
    aboutDescription: "Seva Setu AI is an intelligent, citizen-first civic assistance platform built to simplify Indian public services. Speak naturally in English, Hindi, or Marathi to query welfare schemes, discover required application documents, and draft civic complaints instantly.",
    aboutFoot: "Dedicated to accelerating Digital India inclusion.",
    popularServices: "Popular Services",
    requiredChecklist: "Required Files Checklist",
    verifyDoc: "Verify validity of document details against official registries before submission.",
    describeGrievance: "Describe Grievance (Speak or Type)",
    activeRegion: "📌 Active region: Near Atharva College Area, Malad",
    attachPhoto: "Attach Photo",
    fileComplaintBtn: "Analyze & File Complaint",
    analyzingGrievance: "Analyzing Grievance...",
    complaintTracker: "Complaint Redressal Tracker",
    askCompanion: "Ask AI Companion",
    fullName: "Full Name",
    emailAddress: "Email Address",
    defaultLang: "Default Language",
    changePassword: "Change Password (optional)",
    passwordPlaceholder: "Leave blank to keep same",
    saveSettings: "Save Settings",
    savingSettings: "Saving Settings...",
    chips: [
      { label: 'Passport', query: 'How to apply for an Indian Passport?' },
      { label: 'Aadhaar Card', query: 'What documents are required for Aadhaar updates?' },
      { label: 'PAN Card', query: 'How do I apply for a new PAN card?' },
      { label: 'Scholarships', query: 'What government scholarships are available for students?' },
      { label: 'Pension Schemes', query: 'What pension schemes apply to senior citizens?' }
    ]
  },
  hi: {
    title: "सेवा सेतु AI",
    tagline: "सरकारी सेवाएं। सिर्फ एक बातचीत की दूरी पर।",
    navHome: "मुख्य पृष्ठ",
    navDashboard: "डैशबोर्ड",
    navChat: "AI सहायक",
    navSchemes: "योजनाएं",
    navComplaints: "शिकायतें",
    navDocuments: "दस्तावेज़",
    navProfile: "प्रोफ़ाइल",
    navSettings: "सेटिंग्स",
    navAbout: "हमारे बारे में",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    startTalking: "बातचीत शुरू करें",
    tryDemo: "डेमो देखें",
    heroHeading: "AI के साथ सरकारी सेवाएं हुईं आसान",
    heroSubheading: "अपनी स्थानीय भाषा में स्वाभाविक रूप से बोलें। सरकारी योजनाओं को खोजें, औपचारिक शिकायतें दर्ज करें और आसानी से आवश्यक दस्तावेज़ों की सूची पाएं।",
    featuresTitle: "सेवा सेतु क्यों चुनें?",
    voiceFirst: "आवाज-प्रथम AI",
    voiceFirstDesc: "अंग्रेजी, हिंदी या मराठी में बात करें। किसी टाइपिंग की आवश्यकता नहीं है।",
    docChecklist: "दस्तावेज़ चेकलिस्ट",
    docChecklistDesc: "पासपोर्ट, राशन कार्ड आदि के लिए आवश्यक दस्तावेजों की तत्काल सूची।",
    complaints: "आवाज से शिकायत",
    complaintsDesc: "अपनी नागरिक समस्या का वर्णन करें। AI स्वचालित रूप से एक औपचारिक शिकायत का मसौदा तैयार करता है।",
    schemes: "योजना सलाहकार",
    schemesDesc: "अनुकूल कल्याणकारी योजनाओं को खोजने के लिए अपनी आयु, आय और पेशा दर्ज करें।",
    simpleLang: "सरल भाषा में समझें",
    simpleLangDesc: "जटिल सरकारी प्रक्रियाओं को सरल और स्पष्ट शब्दों में समझें।",
    accessible: "उच्च सुलभता",
    accessibleDesc: "वरिष्ठ नागरिकों, कम साक्षरता वाले लोगों और उच्च कंट्रास्ट दृश्यता के लिए निर्मित।",
    waveformPlaying: "प्रतिक्रिया जोर से पढ़ी जा रही है...",
    stopSpeaking: "बोलना बंद करें",
    listen: "सुनें",
    askQuestion: "सेवा सेतु से कुछ भी पूछें...",
    micTooltip: "बोलने के लिए क्लिक करें",
    listening: "सुन रहा हूँ... अब बोलें",
    processing: "सोच रहा हूँ...",
    normalView: "विस्तृत विवरण",
    simpleView: "सरल विवरण (ELI12)",
    summaryView: "त्वरित सारांश",
    complaintDraft: "तैयार शिकायत का मसौदा",
    complaintDept: "लक्षित विभाग",
    complaintSubject: "विषय",
    complaintIssue: "समस्या",
    complaintDesc: "आधिकारिक विवरण",
    complaintPriority: "प्राथमिकता",
    submitComplaint: "शिकायत दर्ज करें",
    complaintSuccess: "शिकायत सफलतापूर्वक दर्ज की गई!",
    schemeMatch: "आपके लिए व्यक्तिगत योजनाएं",
    schemeEligibility: "कौन आवेदन कर सकता है:",
    schemeBenefits: "लाभ:",
    schemeSteps: "आवेदन के चरण:",
    saveScheme: "योजना बुकमार्क करें",
    savedSchemes: "बुकमार्क की गई योजनाएं",
    recentConversations: "हाल की बातचीत",
    quickActions: "त्वरित कार्य",
    contrastToggle: "हाई कंट्रास्ट मोड",
    textSizeToggle: "अक्षर का आकार",
    textSmall: "A-",
    textNormal: "A",
    textLarge: "A+",
    howItWorksTitle: "सेवा सेतु कैसे काम करता है",
    howItWorksStep1Title: "स्वाभाविक रूप से बोलें",
    howItWorksStep1Desc: "माइक पर टैप करें और अंग्रेजी, हिंदी या मराठी में बोलें। AI अनुवाद करता है और मार्गदर्शिका खोजता है।",
    howItWorksStep2Title: "सरल भाषा में समझें",
    howItWorksStep2Desc: "मानक, सरल (ELI12) या त्वरित बुलेट पॉइंट के बीच स्विच करें। जवाब जोर से सुनें।",
    howItWorksStep3Title: "प्रगति सहेजें",
    howItWorksStep3Desc: "दस्तावेज़ों को चेक करें और कल्याणकारी योजनाओं को सीधे अपने प्रोफाइल में बुकमार्क करें।",
    featuresSub: "सुलभता और डिजिटल समावेशन के लिए डिज़ाइन किया गया",
    langSupport: "अंग्रेजी, हिंदी और मराठी समर्थित",
    heroTitleStart: "आपका अपना",
    heroTitleEnd: "AI सरकारी सहायक",
    heroDescription: "प्रत्येक भारतीय नागरिक को अपनी भाषा में सरकारी सेवाओं तक पहुँचने, योजनाओं को खोजने, शिकायतें दर्ज करने और आधिकारिक दस्तावेजों को समझने में मदद करना।",
    trustVoice: "आवाज प्रथम",
    trustLang: "बहुभाषी",
    trustSecure: "सुरक्षित",
    trustAI: "AI संचालित",
    aboutTitle: "सेवा सेतु AI के बारे में",
    aboutDescription: "सेवा सेतु AI एक बुद्धिमान, नागरिक-प्रथम नागरिक सहायता मंच है जिसे भारतीय सार्वजनिक सेवाओं को सरल बनाने के लिए बनाया गया है। कल्याणकारी योजनाओं की पूछताछ करने, आवश्यक आवेदन दस्तावेजों की खोज करने और तुरंत नागरिक शिकायतों का मसौदा तैयार करने के लिए अंग्रेजी, हिंदी या मराठी में स्वाभाविक रूप से बोलें।",
    aboutFoot: "डिजिटल इंडिया समावेशन को गति देने के लिए समर्पित।",
    popularServices: "लोकप्रिय सेवाएं",
    requiredChecklist: "आवश्यक दस्तावेज़ चेकलिस्ट",
    verifyDoc: "जमा करने से पहले आधिकारिक रजिस्ट्रियों के खिलाफ दस्तावेज़ विवरण की वैधता सत्यापित करें।",
    describeGrievance: "शिकायत का वर्णन करें (बोलें या लिखें)",
    activeRegion: "📌 सक्रिय क्षेत्र: अथर्व कॉलेज क्षेत्र के पास, मलाड",
    attachPhoto: "फ़ोटो संलग्न करें",
    fileComplaintBtn: "विश्लेषण करें और शिकायत दर्ज करें",
    analyzingGrievance: "शिकायत का विश्लेषण किया जा रहा है...",
    complaintTracker: "शिकायत निवारण ट्रैकर",
    askCompanion: "AI साथी से पूछें",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    defaultLang: "डिफ़ॉल्ट भाषा",
    changePassword: "पासवर्ड बदलें (वैकल्पिक)",
    passwordPlaceholder: "समान रखने के लिए खाली छोड़ें",
    saveSettings: "सेटिंग्स सहेजें",
    savingSettings: "सेटिंग्स सहेजी जा रही हैं...",
    chips: [
      { label: 'पासपोर्ट', query: 'भारतीय पासपोर्ट के लिए आवेदन कैसे करें?' },
      { label: 'आधार कार्ड', query: 'आधार अपडेट के लिए कौन से दस्तावेज आवश्यक हैं?' },
      { label: 'पैन कार्ड', query: 'नए पैन कार्ड के लिए आवेदन कैसे करें?' },
      { label: 'छात्रवृत्ति', query: 'छात्रों के लिए कौन सी सरकारी छात्रवृत्तियां उपलब्ध हैं?' },
      { label: 'पेंशन योजनाएं', query: 'वरिष्ठ नागरिकों के लिए कौन सी पेंशन योजनाएं लागू होती हैं?' }
    ]
  },
  mr: {
    title: "सेवा सेतु AI",
    tagline: "शासकीय सेवा. फक्त एका संभाषणाच्या अंतरावर.",
    navHome: "मुख्यपृष्ठ",
    navDashboard: "डॅशबोर्ड",
    navChat: "AI सहाय्यक",
    navSchemes: "योजना",
    navComplaints: "तक्रारी",
    navDocuments: "कागदपत्रे",
    navProfile: "प्रोफाईल",
    navSettings: "सेटिंग्ज",
    navAbout: "आमच्याबद्दल",
    login: "लॉगिन",
    register: "नोंदणी",
    logout: "लॉगआउट",
    startTalking: "संभाषण सुरू करा",
    tryDemo: "डेमो पहा",
    heroHeading: "AI द्वारे शासकीय सेवा आता सोप्या",
    heroSubheading: "तुमच्या स्थानिक भाषेत सहज बोला. शासकीय योजना शोधा, औपचारिक तक्रारींचा मसुदा तयार करा आणि आवश्यक कागदपत्रांची सूची मिळवा.",
    featuresTitle: "सेवा सेतु का निवडावा?",
    voiceFirst: "आवाज-प्रथम AI",
    voiceFirstDesc: "इंग्रजी, हिंदी किंवा मराठीत बोला. टाईप करण्याची गरज नाही.",
    docChecklist: "कागदपत्रांची यादी",
    docChecklistDesc: "पासपोर्ट, रेशन कार्ड इत्यादींसाठी आवश्यक कागदपत्रांची त्वरित यादी.",
    complaints: "आवाज तक्रार मसुदा",
    complaintsDesc: "तुमच्या नागरी समस्येचे वर्णन करा. AI स्वयंचलितपणे अधिकृत तक्रार मसुदा तयार करेल.",
    schemes: "योजना सल्लागार",
    schemesDesc: "जुळणाऱ्या कल्याणकारी योजना शोधण्यासाठी consume तुमचे वय, उत्पन्न आणि व्यवसाय प्रविष्ट करा.",
    simpleLang: "सोप्या भाषेत स्पष्टीकरण",
    simpleLangDesc: "क्लिष्ट शासकीय प्रक्रिया सोप्या आणि सुटसुटीत भाषेत वाचा.",
    accessible: "उच्च सुलभता",
    accessibleDesc: "ज्येष्ठ नागरिक, कमी साक्षरता असलेल्या व्यक्ती आणि उच्च कॉन्ट्रास्ट सुलभतेसाठी डिझाइन केलेले.",
    waveformPlaying: "उत्तर मोठ्याने वाचले जात आहे...",
    stopSpeaking: "बोलणे थांबवा",
    listen: "ऐका",
    askQuestion: "सेवा सेतूला काहीही विचारा...",
    micTooltip: "बोलण्यासाठी क्लिक करा",
    listening: "ऐकत आहे... आता बोला",
    processing: "प्रक्रिया सुरू आहे...",
    normalView: "सविस्तर स्पष्टीकरण",
    simpleView: "सोपे स्पष्टीकरण (ELI12)",
    summaryView: "थोडक्यात सारांश",
    complaintDraft: "तयार केलेला तक्रार मसुदा",
    complaintDept: "संबंधित विभाग",
    complaintSubject: "विषय",
    complaintIssue: "समस्या",
    complaintDesc: "अधिकृत वर्णन",
    complaintPriority: "प्राधान्य",
    submitComplaint: "तक्रार सबमिट करा",
    complaintSuccess: "तक्रार यशस्वीरित्या नोंदवली गेली!",
    schemeMatch: "तुमच्यासाठी शिफारस केलेल्या योजना",
    schemeEligibility: "कोण अर्ज करू शकतो:",
    schemeBenefits: "फायदे:",
    schemeSteps: "अर्जाच्या पायऱ्या:",
    saveScheme: "योजना बुकमार्क करा",
    savedSchemes: "बुकमार्क केलेल्या योजना",
    recentConversations: "अलीकडील संभाषणे",
    quickActions: "त्वरित कृती",
    contrastToggle: "हाय कॉन्ट्रास्ट मोड",
    textSizeToggle: "अक्षराचा आकार",
    textSmall: "A-",
    textNormal: "A",
    textLarge: "A+",
    howItWorksTitle: "सेवा सेतु कसे काम करते",
    howItWorksStep1Title: "सहज बोला",
    howItWorksStep1Desc: "माईक दाबा आणि इंग्रजी, हिंदी किंवा मराठीत बोला. AI भाषांतर करून मार्गदर्शक तत्त्वे शोधेल.",
    howItWorksStep2Title: "सोप्या भाषेत स्पष्टीकरण",
    howItWorksStep2Desc: "प्रमाणित, सोपे (ELI12) किंवा मुख्य मुद्द्यांमध्ये स्विच करा. उत्तर ऐका.",
    howItWorksStep3Title: "प्रगती जतन करा",
    howItWorksStep3Desc: "कागदपत्रांची पडताळणी करा आणि शिफारस केलेल्या योजना थेट प्रोफाईलवर सेव्ह करा.",
    featuresSub: "सुलभता आणि डिजिटल समावेशनासाठी डिझाइन केलेले",
    langSupport: "इंग्रजी, हिंदी आणि मराठी समर्थित",
    heroTitleStart: "तुमचा वैयक्तिक",
    heroTitleEnd: "AI सरकारी सहाय्यक",
    heroDescription: "प्रत्येक भारतीय नागरिकाला त्याच्या स्वतःच्या भाषेत सरकारी सेवा मिळवण्यास, योजना शोधण्यास, तक्रारी दाखल करण्यास आणि अधिकृत कागदपत्रे समजून घेण्यास मदत करणे.",
    trustVoice: "आवाज प्रथम",
    trustLang: "बहुभाषिक",
    trustSecure: "सुरक्षित",
    trustAI: "AI संचालित",
    aboutTitle: "सेवा सेतु AI बद्दल",
    aboutDescription: "सेवा सेतु AI हे भारतीय सार्वजनिक सेवा सुलभ करण्यासाठी बनवलेले एक बुद्धिमान, नागरिक-प्रथम नागरी सहाय्य व्यासपीठ आहे. कल्याणकारी योजनांची चौकशी करण्यासाठी, आवश्यक अर्ज दस्तऐवज शोधण्यासाठी आणि नागरी तक्रारींचा मसुदा त्वरित तयार करण्यासाठी इंग्रजी, हिंदी किंवा मराठीमध्ये सहज बोला.",
    aboutFoot: "डिजिटल इंडिया समावेशन वाढवण्यासाठी समर्पित.",
    popularServices: "लोकप्रिय सेवा",
    requiredChecklist: "आवश्यक कागदपत्रे चेकलिस्ट",
    verifyDoc: "सबमिट करण्यापूर्वी अधिकृत रजिस्ट्रीसह कागदपत्रांच्या तपशीलांची वैधता तपासा.",
    describeGrievance: "तक्रारीचे वर्णन करा (बोला किंवा लिहा)",
    activeRegion: "📌 सक्रिय क्षेत्र: अथर्व कॉलेज क्षेत्राजवळ, मलाड",
    attachPhoto: "फोटो जोडा",
    fileComplaintBtn: "तपासणी करा आणि तक्रार नोंदवा",
    analyzingGrievance: "तक्रारीची तपासणी केली जात आहे...",
    complaintTracker: "तक्रार निवारण ट्रॅकर",
    askCompanion: "AI सोबतीला विचारा",
    fullName: "पूर्ण नाव",
    emailAddress: "ईमेल पत्ता",
    defaultLang: "डीफॉल्ट भाषा",
    changePassword: "पासवर्ड बदला (पर्यायी)",
    passwordPlaceholder: "तेच ठेवण्यासाठी रिकामे सोडा",
    saveSettings: "सेटिंग्ज जतन करा",
    savingSettings: "सेटिंग्ज जतन केल्या जात आहेत...",
    chips: [
      { label: 'पासपोर्ट', query: 'भारतीय पासपोर्टसाठी अर्ज कसा करावा?' },
      { label: 'आधार कार्ड', query: 'आधार अपडेटसाठी कोणती कागदपत्रे आवश्यक आहेत?' },
      { label: 'पॅन कार्ड', query: 'नवीन पॅन कार्डसाठी अर्ज कसा करावा?' },
      { label: 'शिष्यवृत्ती', query: 'विद्यार्थ्यांसाठी कोणत्या सरकारी शिष्यवृत्ती उपलब्ध आहेत?' },
      { label: 'पेन्शन योजना', query: 'वरिष्ठ नागरिकांसाठी कोणत्या पेन्शन योजना लागू होतात?' }
    ]
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('seva_setu_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('seva_setu_lang', language);
  }, [language]);

  const t = translations[language] || translations['en'];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
